lxc/nova-lxd

nclxd/cmd/converter.py

Fixed three minor issues:
- Removed duplicate tar parameter (--numeric owner)
- Fixed issue where tar did not get --exclude=dev/* parameter and spewed error messages when run non-root
- Removed 'v' flag from tar create, unneeded debugging.

Minor fixes to converter

---

nclxd/nova/virt/lxd/container_image.py

nclxd should not be updating the metadata on a glance image; this
actually causes problems with image creation on subsequent
container creation events on different compute hosts, as the
presence of lxd-image-alias causes the image creation to not
happen.
Closes-Bug: 1499232

Drop update for glance image metadata

---

nclxd/nova/virt/lxd/container_image.py

Fix traceback when handling image_properties

Fix image_properties handling

---

nclxd/nova/virt/lxd/container_ops.py
nclxd/tests/test_driver_api.py

unplug vifs was incorrectly calling plug
also no cleanup for plugged vifs on destruction.

Ensure vifs are unplugged and destroyed appropriately

---

nclxd/nova/virt/lxd/vif.py

Fix vif creation

---

nclxd/nova/virt/lxd/container_ops.py
nclxd/nova/virt/lxd/container_utils.py
nclxd/tests/fake_api.py
nclxd/tests/test_container_utils.py

operation_wait will always return success (as it indicates the success
of the wait, rather than the operation itself), so we need to query
the operation info when wait completes.
Raise an appropriate exception when container creation fails.

Handle container initialization failure

---

nclxd/nova/virt/lxd/container_config.py
nclxd/nova/virt/lxd/container_migrate.py
nclxd/nova/virt/lxd/container_ops.py
nclxd/nova/virt/lxd/container_snapshot.py
nclxd/nova/virt/lxd/container_utils.py
nclxd/nova/virt/lxd/driver.py
nclxd/nova/virt/lxd/vif.py
nclxd/tests/test_container_config.py
nclxd/tests/test_container_migration.py

Due to commit bbf6380acc937bf4df302b3 instnace.uuid is no
longer a valid name for a container. Transition to
instance.name

Transition to use instance.name

---

nclxd/nova/virt/lxd/container_config.py
nclxd/nova/virt/lxd/container_ops.py
nclxd/tests/test_container_ops.py

Refactor network creation so that when the container config
is made include the network information.

Refactor network creation

---

nclxd/nova/virt/lxd/container_snapshot.py
nclxd/tests/test_driver_api.py

Use the image_meta.id when creating a snapshot image,
otherwise container creation will fail with a bad image_ref.
This was caused by the fallout from instance.name -> instance.uuid.
Fixes issue #56

Use snapshot id when creating images

---

nclxd/nova/virt/lxd/container_config.py
nclxd/nova/virt/lxd/container_migrate.py
nclxd/nova/virt/lxd/container_utils.py
nclxd/nova/virt/lxd/driver.py
nclxd/tests/test_container_migration.py
nclxd/tests/test_driver_api.py

Fix contianer migration and resize, there is no need to resize
a container "disk" right now since flavor.disk is not supported.
Also do the migration last before everything is ready.

Fix container migration and resize

---

nova_lxd/nova/virt/lxd/container_config.py
nova_lxd/nova/virt/lxd/container_image.py
nova_lxd/nova/virt/lxd/container_ops.py
nova_lxd/nova/virt/lxd/container_utils.py
nova_lxd/nova/virt/lxd/utils.py
nova_lxd/tests/test_container_config.py
nova_lxd/tests/test_driver_api.py

Split out LXDContianerDirectories and LXDContainerUtils

Split out LXDContainerDirectories

---

nova_lxd/tests/test_driver_api.py

Fix unit tests on non-x86_64 arch. The value
was being hardcoded in the tests.

Fix arch on non-x86_64 arches

---

nova_lxd/nova/virt/lxd/host.py
nova_lxd/tests/test_driver_api.py

Use socket.getfqdn() to return the FQDN hostname.
Fixes issue #77.

Use hostname fqdn

---

nova_lxd/nova/virt/lxd/host.py
nova_lxd/tests/test_driver_api.py

LXD is in nova's recognized hypervisor list,
so use it.

Use LXD as hypervisor type

---

nova_lxd/nova/virt/lxd/host.py
nova_lxd/tests/test_driver_api.py

If FQDN is not setup correctly, then compute is not able
to manage the node correctly.

Use socket.gethostname()

---

nova_lxd/nova/virt/lxd/session/image.py

Previous versions of LXD (below 0.22) does not send
an operation id. So check to see if we have an operation id
before waiting for the image upload to finish.

Check for container operation in iamge_upload

---

nova_lxd/nova/virt/lxd/host.py
nova_lxd/tests/test_driver_api.py

JSON encoding for supported_instances in the virt
drivers was a temporary measure that is not needed.
The encoding has been removed for all in tree virt
drivers. This patch removes the code that checks
for JSON encoding in the compute node object.
Apart of blueprint mitaka-objects

Drop JSON encoding for supported_instances

---

nova_lxd/nova/virt/lxd/vif.py

In nova_lxd/nova/virt/lxd/vif.py, the bridge doesn't created, because the else: in plug_bridge belongs to the wrong "if". Seems it is a bad copy-paste from nova libvirt vif.py.

Fix bridge creation with LinuxBridge

---

nova_lxd/nova/virt/lxd/config.py
nova_lxd/nova/virt/lxd/session.py
nova_lxd/tests/test_config.py

Check for LXD block device type before trying
to set the quota.

Check for LXD block devices

---

nova_lxd/nova/virt/lxd/config.py
nova_lxd/nova/virt/lxd/host.py
nova_lxd/nova/virt/lxd/migrate.py
nova_lxd/nova/virt/lxd/operations.py
nova_lxd/nova/virt/lxd/session.py
nova_lxd/tests/session/test_container.py
nova_lxd/tests/test_config.py
nova_lxd/tests/test_driver_api.py

Summary of Changes in this branch:
- Fix launching of configdrive:  When launching an instance with configdrive, LXD expects a
string rather than an boolean value. Otherwise the instance wont boot. This should be caught better by writing better unit tests.
- Fix issue #20 - Fixes a traceback when running get_host_cpu_stats.  Things like this will need better unit tests in the future.
- Remove extra LXD console configuration parameters. Previous versions need extra cgroup parameters in order to access the LXD container console. This is no longer required.
- Migration configdrive fixes.  When resizing and migrating a container to a different host, the hosts configdrive mounts is not copied as well. So recreate the configdrive directories on the new host before initializing the container.
- …

Bugfixes and resource updates

---

nova_lxd/nova/virt/lxd/image.py
nova_lxd/tests/test_image.py

Check for root-tar image format as well as raw.

Update check for image format

---

nova_lxd/nova/virt/lxd/operations.py
nova_lxd/tests/test_driver_api.py

When attachnig a directory it must have the same permissions for the configdrive
so that the user can access files. In this case, the configdrive permissions were
not correct so the user was not able to ssh into the instances with their
ssh keys.

Adjust permissions for configdrive

---

.travis.yml
test-requirements.txt
tox.ini

It was preventing devstack from installing correctly.

Move test-requirements to tox.ini

---

contrib/glance_metadefs/compute-lxd-flavor.json

The importable Glance metadefs are not only a convenient way to pass metadata from Horizon; they also help in documenting the project's metadata namespace. This metadata definition exposes the "lxd:nested_allowed" and "lxd:privileged_allowed" properties to flavors.

importable Glance metadata definition file

---

tox.ini

A generic python 3 will suffice.

No python 3.4 on xenial

---

nova/tests/unit/virt/lxd/test_driver_api.py
nova/virt/lxd/driver.py

Add check for driver compatibility for 'supports_attach_interface'.

Sync with compute driver

---

nova/tests/unit/virt/lxd/test_config.py
nova/virt/lxd/config.py

The OS::Compute::Quota metadata namespace defines Disk, NIC and CPU quotas that are passed to the hypervisor (currently only Libvirt) via flavor metadata. This PR implements just two of them - NIC and Disk - because I didn't find a way to sensibly translate the CPU quota parameters to the LXD world.
However, the Disk and NIC quotas are fairly well understood by LXD and allow us to control container throughput to disks or network in Bytes/s or IOps.

Disk and NIC quotas

---

nova/virt/lxd/session.py

When the LXD API returns an error during instance creation, the actual error message is passed in data['metadata']['err'], not data['metadata']['metadata'].
Even worse metadata might be empty, in which case Nova will only show "An unknown exception occured".
This change turned "An unknown exception occured" (even with highest debug logging) into "btrfs quotas not supported. Try enabling them with 'btrfs quota enable'.".
My fix is pretty rough, because I do not understand the reasoning behind the original code. In all my tests this field was empty, while 'err' contained the error message, but you never know.
(Also, line 532: Why is data.get('metadata') used instead of regular item access? If 'metadata' is not in data, the next line will fail anyway...)

Show actual error message when LXD API fails

---

nova/tests/unit/virt/lxd/test_config.py
nova/virt/lxd/config.py

Having done some practical tests, I came about an error in a previous commit. The compute quota metadata interface asks users to input network quotas in Kilobytes/s, while LXD expects *bits/s. So in the end we have to multiply user input by (8 * units.k).

fixed unit conversions in network quotas

---

nova/tests/unit/virt/lxd/test_session.py
nova/virt/lxd/operations.py
nova/virt/lxd/session.py
nova/virt/lxd/utils.py

Remove code that is no longer needed, used, and just plain ugly.
- Remove dead code specifically mount/umounting filesy stems. This is no longer used.
- Remove old directory detection that is no longer used or needed.
- Remove container_defined from where it is "overkill". This was done in preparation for pylxd 2.0 since it is handled in a different way. Also update unit tests to reflect this change.

Code tidyness

---

nova/tests/unit/virt/lxd/test_driver_api.py
nova/virt/lxd/container_firewall.py
nova/virt/lxd/container_snapshot.py
nova/virt/lxd/driver.py
nova/virt/lxd/host.py
nova/virt/lxd/image.py
nova/virt/lxd/operations.py
nova/virt/lxd/utils.py
nova/virt/lxd/vif.py

In the mitaka cycle, nova.conf has centralized all
the Nova configuration options in one place. Transition
nova-lxd to use nova.conf to access configuration
options.

Transition to nova.conf
