nclxd/nova/virt/lxd/container_config.py
nclxd/nova/virt/lxd/container_image.py
nclxd/nova/virt/lxd/container_ops.py
nclxd/nova/virt/lxd/container_utils.py
nclxd/nova/virt/lxd/driver.py
nclxd/nova/virt/lxd/host.py
nclxd/tests/__init__.py
nclxd/tests/test_container_ops.py
nclxd/tests/test_container_utils.py

Drop redundant lxd

---

nclxd/nova/virt/lxd/container_config.py
nclxd/nova/virt/lxd/container_firewall.py
nclxd/nova/virt/lxd/container_ops.py
nclxd/nova/virt/lxd/container_utils.py
nclxd/nova/virt/lxd/driver.py
nclxd/tests/test_driver_api.py

More driver tests

---

nclxd/nova/virt/lxd/container_config.py

Update attach interface to use the new vif config.

Update attach interface

---

nclxd/nova/virt/lxd/container_client.py
nclxd/nova/virt/lxd/container_config.py
nclxd/nova/virt/lxd/container_ops.py
nclxd/nova/virt/lxd/container_utils.py

Refactor container rescue and unrescue

Rescue unrescue

---

nclxd/nova/virt/lxd/container_image.py

If multiple instances attempt to boot the same image, the first succeeds, and the rest fail.
By locking image upload activity around each image uuid, we ensure that the first attempt uploads and creates the alias, and subsequent calls queue whilst that happens.
I also trimmed out the check for lxd_image_alias and altered the handling of tarballs already on disk to remove and re-download if found.

Ensure image upload activities are guarded against concurrency

---

nclxd/nova/virt/lxd/container_image.py
nclxd/nova/virt/lxd/container_utils.py
nclxd/tests/test_container_image.py

Generate the lxd manifest from the image-properties from glance.

Generate the lxd manifest from the image-properties from glance.

---

nclxd/nova/virt/lxd/container_migrate.py
nclxd/nova/virt/lxd/container_ops.py
nclxd/nova/virt/lxd/container_utils.py
nclxd/tests/fake_api.py
nclxd/tests/test_container_utils.py
nclxd/tests/test_driver_api.py
setup.cfg

Various fixes for container_utils and adding unit tests.

Various container_utils fixes

---

nclxd/nova/virt/lxd/container_client.py

Re-add timeout for container reboot.

Re-add timeout

---

nclxd/nova/virt/lxd/container_config.py
nclxd/nova/virt/lxd/container_ops.py
nclxd/nova/virt/lxd/container_utils.py
nclxd/tests/test_container_config.py

Fix container rescue/unrescue with lvm

Fix container rescue/unrescue with lvm

---

nclxd/nova/virt/lxd/container_config.py
nclxd/tests/test_container_config.py

Remove cpu limits as they are not quite working properly with LXD.

Remove cpu limits

---

nclxd/nova/virt/lxd/container_snapshot.py
nclxd/nova/virt/lxd/container_utils.py
nclxd/tests/test_container_ops.py
nclxd/tests/test_driver_api.py

Pass the full operaiton url. Due to this change in pylxd
https://github.com/lxc/pylxd/commit/2f630afd7d091af48b91ef48127f5dd7ca9d0a9c

Pass the full operation url

---

nova_lxd/nova/virt/lxd/container_image.py

Fingerprint was not being set back from LXD so
generate fingerprint from the files downloaded from
glance.

Fix alias creation

---

nova_lxd/nova/virt/lxd/container_image.py

Wait for container upload before setup alias.

Wait for container upload

---

nova_lxd/nova/virt/lxd/constants.py
nova_lxd/nova/virt/lxd/container_config.py
nova_lxd/nova/virt/lxd/session/container.py
nova_lxd/nova/virt/lxd/session/event.py
nova_lxd/nova/virt/lxd/session/snapshot.py

Fix nitpicks such as spelling and grammar usage. No actual code change

Fix nitpicks

---

setup.cfg

Bump to v0.19

---

CONTRIBUTING.rst

Hacking docs

---

setup.cfg

Bump version to 13.0.0b2

---

nova_lxd/nova/virt/lxd/config.py
nova_lxd/nova/virt/lxd/migrate.py
nova_lxd/tests/test_config.py

Various bugfixes uncovered by several rally runs.

Rally bugfixes

---

nova_lxd/nova/virt/lxd/config.py
nova_lxd/tests/test_config.py

Resolves conflict with ComputeCapabilitiesFilter
#60

use lxd: namespace for flavor extra_specs

---

README.md

Doc: improve README.md

---

nova/virt/lxd/driver.py

Sync Compute Driver

---

devstack/local.conf.sample

Update devstack configuration to add q-l3.

Update devstack local.conf.sample

---

README.md

Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

Fix rendering of README.md
